---
- name: "Install and run supermario docker image"
  become: no
  hosts: prod
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Include vars
      include_vars: resources/vars.yml

    - name: Create directory
      file:
        state: directory
        path: /home/vagrant/deploy_webapps

    - name: Copy config file to build image
      copy:
        src: resources/{{item}}
        dest: /home/vagrant/deploy_webapps/{{item}}
      loop:
        - Dockerfile
        - nginx.conf
        - vars.yml
#      notify: Docker Build Files Changed
#   - meta: flush_handlers

    - name: Docker Build Files Changed
      docker_image:
        name: "{{IMAGE_NAME}}"
        build:
          path: /home/vagrant/deploy_webapps
          dockerfile: /home/vagrant/deploy_webapps/Dockerfile
        source: build

    - name: Run container
      docker_container:
        name: "{{IMAGE_NAME}}"
        image: "{{IMAGE_NAME}}"
        published_ports: "0.0.0.0:{{PORT}}:{{PORT_EXPOSED}}"
        env:
           PORT: "{{PORT_EXPOSED}}"
        state: started

#  handlers:
#    - name: Docker Build Files Changed
#      docker_container:
#        name: "{{IMAGE_NAME}}"
#        image: "{{IMAGE_NAME}}"
#        state: absent
        
#    - name: Docker Build Files Changed
#      docker_image:
#        name: "{{IMAGE_NAME}}"
#        build: 
#          path: /home/vagrant/deploy_webapps
#          dockerfile: /home/vagrant/deploy_webapps/Dockerfile
#        source: build

